---
language: python
python: "2.7"

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: ppa:ansible/ansible
    packages:
      - ansible

before_install: cd tests

install:
  - pip install molecule
  - ansible-galaxy install -r roles.yml

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
