---
# tasks file for tmux-tpm
- name: mkdir ~/.tmux/plugins
  file:
    path: "{{ansible_env.HOME}}/.tmux/plugins"
    state: directory
- name: Clone tpm
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ansible_env.HOME}}/.tmux/plugins/tpm"
